import { Inter } from "next/font/google";

import Navbar from "@/components/Navbar";
import Foother from "@/components/Foother";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />

        <section className="bg-neutral-600 h-96">
          <h1>The blass store</h1>
        </section>
        {children}
        <Foother />
      </body>
    </html>
  );
}
